### ISSUE TITLE
Do we handle JWT expiry correctly?

### ISSUE THREAD

**Issue by literalplus** [xxyy/tingo#2]
````
2018-04-03 03:00:11.467 ERROR 5818 --- [http-nio-7331-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

io.jsonwebtoken.ExpiredJwtException: JWT expired at 2018-03-04T22:51:28+0100. Current time: 2018-04-03T03:00:01+0200
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:365) ~[jjwt-0.6.0.jar!/:0.6.0]
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:458) ~[jjwt-0.6.0.jar!/:0.6.0]
        at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:518) ~[jjwt-0.6.0.jar!/:0.6.0]
        at li.l1t.tingo.security.auth.TokenHandler.parseUserFromToken(TokenHandler.java:34) ~[tingo.jar!/:na]
        at li.l1t.tingo.security.auth.JwtAuthenticationFilter.attemptAuthentication(JwtAuthenticationFilter.java:66) ~[tingo.jar!/:na]
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
````

**Comment by ghost** [comment]
[JWT library and handle expiration ExpiredJWTException](https://stackoverflow.com/questions/49085433/jjwt-library-and-handle-expiration-expiredjwtexception)

**Comment by literalplus** [comment]
Thanks for adding additional information to this issue!
